load("//build/install:install.bzl", "install")

package(
    default_visibility = ["//visibility:public"],
)

install(
    name = "install",
    deps = [
        "//tools/cyber_launch:install",
        "//tools/cyber_monitor:install",
        "//tools/cyber_recorder:install",
        "//tools/cyber_channel:install",
    ],
)
